# Custom commands

# Syntax: command-alias[<index>] <name> = '<definition>'

set -g command-alias[100] help='display-popup -E "${PAGER} ~/.tmux.conf"'
set -g command-alias[101] reload='if-shell \
    "tmux source-file ${HOME}/.tmux.conf" \
    "display-message \"Configuration reloaded!\"" \
    "display-message \"Failed to reload configuration\""'

set -g command-alias[110] vert-split='split -h'
set -g command-alias[111] vsp='split -h'
